In [1]:
from fuzzy import *
import matplotlib.pyplot as plt
import pandas as pd
import math
import random
from sklearn.model_selection import train_test_split


In [2]:
df = pd.read_csv('iris-versicolor.csv')

df = df.sample(frac=1)


X = df.iloc[:, 1:3].values
Y = df.iloc[:,0].values
X

array([[4.4, 3.2],
       [6.3, 2.5],
       [5.1, 3.3],
       [5.6, 3. ],
       [5.1, 3.5],
       [5.9, 3. ],
       [6.7, 3. ],
       [6.2, 3.4],
       [4.3, 3. ],
       [6.3, 3.3],
       [6. , 2.9],
       [5.2, 2.7],
       [6.4, 3.1],
       [5.6, 3. ],
       [6.8, 2.8],
       [6.9, 3.1],
       [6.1, 2.6],
       [6.7, 3.3],
       [6.6, 2.9],
       [5.6, 2.7],
       [5.4, 3. ],
       [6.5, 2.8],
       [6.7, 3.3],
       [6.2, 2.2],
       [5.7, 2.8],
       [7.9, 3.8],
       [5.8, 2.7],
       [6.7, 3.1],
       [5.2, 3.5],
       [6.4, 2.8],
       [5.8, 2.7],
       [4.8, 3.4],
       [7. , 3.2],
       [5. , 3.3],
       [6.6, 3. ],
       [6.3, 2.5],
       [5.1, 2.5],
       [6.7, 3.1],
       [4.9, 3.1],
       [5.2, 3.4],
       [6.1, 3. ],
       [5.4, 3.4],
       [5.1, 3.5],
       [5. , 3.6],
       [7.3, 2.9],
       [6.3, 2.8],
       [6.3, 2.7],
       [5.4, 3.9],
       [6.7, 3. ],
       [4.8, 3.4],
       [5.5, 2.6],
       [6. , 3. ],
       [6.1,

In [3]:
xTrain, xTest, yTrain, yTest = train_test_split(X,Y)

In [4]:
xTrain.shape, xTest.shape

((112, 2), (38, 2))

In [5]:
def mean_squared_error(self, X, Y):

		res = []
		for x, y in zip(X, Y):
			_, pred = self.predict(x)
			res.append(pred)

		return mean_squared_error(Y, res)

In [6]:
model = FuzzyMMC(sensitivity=1, exp_bound=0.1, animate=False)

In [7]:
model.fit(xTrain, yTrain)

In [8]:
model.score(xTest, yTest) 

0.631578947368421

In [9]:
model.mean_squared_error(xTest, yTest)

0.3684210526315789

In [10]:
x = xTest[9]

membership, max_memb, pred = model.predict(x)
(membership, max_memb, pred)

([0.9750000000000001, 0.975], 0.9750000000000001, 0)

In [11]:
yTest[9]

0

In [12]:
a = np.arange (0.0, 1.1, 0.1)
parameters = {'sensitivity': a, 'exp_bound': a }
parameters['exp_bound']

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [13]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(model, parameters, cv = 5)

In [14]:
clf.fit(xTrain, yTrain)

C:\Users\rita folisi\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=<fuzzy.FuzzyMMC object at 0x00000280D4FB7148>,
             iid='warn', n_jobs=None,
             param_grid={'exp_bound': array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]),
                         'sensitivity': array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [15]:
clf.cv_results_

{'mean_fit_time': array([0.22562222, 0.1727263 , 0.18982282, 0.17113485, 0.17553687,
        0.2359551 , 0.22752643, 0.16934547, 0.17712536, 0.20333958,
        0.17612996, 0.11334991, 0.09846659, 0.10096912, 0.09473724,
        0.09685774, 0.09598207, 0.09931812, 0.09577656, 0.09393239,
        0.11369071, 0.10951695, 0.07044673, 0.06403461, 0.06004786,
        0.06143675, 0.0610538 , 0.06026673, 0.0622293 , 0.06381426,
        0.06235504, 0.06745734, 0.06762505, 0.06225471, 0.0462677 ,
        0.05509901, 0.06343212, 0.07733254, 0.06588302, 0.06693969,
        0.06516867, 0.04548554, 0.05484672, 0.0480341 , 0.03225203,
        0.04446926, 0.03653712, 0.03067975, 0.05296764, 0.03385859,
        0.03269143, 0.05069447, 0.04466414, 0.0357131 , 0.02992105,
        0.04292674, 0.03290148, 0.03071771, 0.03112683, 0.02451468,
        0.02554045, 0.0311367 , 0.03114843, 0.03233309, 0.03250866,
        0.0298799 , 0.03053236, 0.0287322 , 0.02602859, 0.02865133,
        0.02611632, 0.02731905,

In [16]:
clf.score(xTest, yTest) 

0.631578947368421

In [17]:
best_params = clf.best_params_
new_exp = best_params['exp_bound']
new_sensit = best_params['sensitivity']
(new_exp, new_sensit)

(0.1, 0.30000000000000004)

In [18]:
best_model = FuzzyMMC(sensitivity=new_sensit, exp_bound=new_exp, animate=False)

In [19]:
best_model.fit(xTrain, yTrain)

In [20]:
best_model.score(xTest, yTest)

0.631578947368421

In [21]:
	def MSE_membership2(self, X, Y):

		res = []
		for x, y in zip(X, Y):
			pred, _, _ = self.predict(x)
			res.append(pred)
		res = np.array(res)
		return res, mean_squared_error(Y, res[:, 1]) 

In [22]:
from sklearn.metrics import mean_squared_error
res, val = MSE_membership2(model, xTest, yTest)
val

0.4443421052631579

Ho una MSE della membership così alta perché in generale le membership sono molto alte. Quindi pur avendo alta accuratezza, avrò comunque alto MSE delle membership. Vedi sotto:

In [23]:
res

array([[1.   , 0.95 ],
       [0.95 , 0.65 ],
       [0.9  , 0.75 ],
       [1.   , 0.8  ],
       [0.875, 0.95 ],
       [0.925, 1.   ],
       [1.   , 0.775],
       [0.975, 0.75 ],
       [1.   , 0.825],
       [0.975, 0.975],
       [1.   , 0.95 ],
       [0.975, 0.75 ],
       [0.975, 0.975],
       [0.95 , 0.975],
       [0.975, 0.75 ],
       [0.95 , 0.975],
       [0.95 , 0.975],
       [0.95 , 0.75 ],
       [0.925, 0.775],
       [0.875, 0.95 ],
       [0.975, 0.9  ],
       [0.95 , 0.925],
       [0.95 , 0.9  ],
       [0.9  , 0.65 ],
       [0.95 , 0.9  ],
       [0.975, 0.9  ],
       [1.   , 0.925],
       [0.95 , 0.825],
       [0.95 , 0.975],
       [0.975, 0.975],
       [0.975, 0.975],
       [0.975, 0.75 ],
       [0.875, 1.   ],
       [0.975, 0.85 ],
       [0.925, 1.   ],
       [0.95 , 0.975],
       [1.   , 0.85 ],
       [0.975, 0.975]])

In [24]:
res [:, 1]    
# vettore delle membership di xTest. [:, 1] indica quelle relative all'appartenenza a setosa. 
# Quindi indica quanto è effettivamente setosa

array([0.95 , 0.65 , 0.75 , 0.8  , 0.95 , 1.   , 0.775, 0.75 , 0.825,
       0.975, 0.95 , 0.75 , 0.975, 0.975, 0.75 , 0.975, 0.975, 0.75 ,
       0.775, 0.95 , 0.9  , 0.925, 0.9  , 0.65 , 0.9  , 0.9  , 0.925,
       0.825, 0.975, 0.975, 0.975, 0.75 , 1.   , 0.85 , 1.   , 0.975,
       0.85 , 0.975])

In [25]:
res [:, 0]   # indica quanto effettivamente non è setosa

array([1.   , 0.95 , 0.9  , 1.   , 0.875, 0.925, 1.   , 0.975, 1.   ,
       0.975, 1.   , 0.975, 0.975, 0.95 , 0.975, 0.95 , 0.95 , 0.95 ,
       0.925, 0.875, 0.975, 0.95 , 0.95 , 0.9  , 0.95 , 0.975, 1.   ,
       0.95 , 0.95 , 0.975, 0.975, 0.975, 0.875, 0.975, 0.925, 0.95 ,
       1.   , 0.975])

In [26]:
yTest

array([1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

Crossvalidation modificata

In [49]:
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.metrics import classification_report, mean_squared_error
from sklearn.metrics import accuracy_score
from sklearn.utils import shuffle

df = pd.read_csv('iris-setosa.csv')


X = df.iloc[:, 1:3].values
y = df.iloc[:,0].values

seed = 10
X, y = shuffle(X, y, random_state=seed)

a = np.arange (0.0, 1.1, 0.1)
parameters = {'sensitivity': a, 'exp_bound': a }
N_SPLIT = 5
err = []
acc = []


skf = StratifiedKFold(n_splits=N_SPLIT, shuffle=False, random_state=5)
for train_index, validation_index in skf.split(X, y):
    print(train_index)
    X_train, X_validation = X[train_index], X[validation_index]
    y_train, y_validation = y[train_index], y[validation_index]
    
    model = FuzzyMMC(sensitivity=1, exp_bound=0.1, animate=False)
    clf = GridSearchCV(model, parameters, cv=5)
    clf.fit(X_train, y_train)
    best_model = clf.best_estimator_
    best_model.fit(X_train, y_train)
    acc.append(best_model.score(X_validation, y_validation))
    _, val = MSE_membership2(best_model, X_validation, y_validation)
    err.append(val)

[ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47
  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  57  59  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
[  0   1   2   3   4   5

In [50]:
acc

[1.0, 0.9666666666666667, 1.0, 1.0, 1.0]

In [51]:
err

[0.635226875,
 0.6334599999999999,
 0.6357210416666665,
 0.6347424999999998,
 0.633445625]