In [1]:
from fuzzy import *
import matplotlib.pyplot as plt
import pandas as pd
import math
import random
from sklearn.model_selection import train_test_split


In [2]:
df = pd.read_csv('iris-versicolor.csv')

df = df.sample(frac=1)


X = df.iloc[:, 1:3].values
Y = df.iloc[:,0].values
X

array([[5. , 3.4],
       [6.4, 2.9],
       [6.4, 2.8],
       [5.5, 2.3],
       [6.3, 2.5],
       [6.8, 3.2],
       [6. , 2.2],
       [5.6, 2.8],
       [6. , 3.4],
       [5.5, 4.2],
       [6.6, 3. ],
       [6.1, 3. ],
       [6.2, 2.2],
       [6.9, 3.1],
       [5.1, 3.5],
       [6.7, 2.5],
       [5.7, 2.8],
       [5.9, 3. ],
       [5. , 3.3],
       [6.1, 2.9],
       [4.8, 3.4],
       [7.2, 3.6],
       [6. , 2.2],
       [5.5, 2.4],
       [5.5, 3.5],
       [4.9, 3.1],
       [5.2, 3.4],
       [6.5, 3. ],
       [4.7, 3.2],
       [5.1, 3.7],
       [5.8, 2.8],
       [7.3, 2.9],
       [6.4, 3.1],
       [5. , 2.3],
       [5.1, 3.4],
       [5.4, 3.9],
       [5.4, 3.9],
       [5.1, 2.5],
       [4.8, 3.4],
       [6.3, 2.8],
       [6.9, 3.1],
       [5. , 3.4],
       [5. , 3. ],
       [5.6, 2.5],
       [5.1, 3.8],
       [6.8, 2.8],
       [6.4, 3.2],
       [5.7, 4.4],
       [5.7, 2.8],
       [5.4, 3.7],
       [6.9, 3.1],
       [7.6, 3. ],
       [5.4,

In [3]:
xTrain, xTest, yTrain, yTest = train_test_split(X,Y)

In [4]:
xTrain.shape, xTest.shape

((112, 2), (38, 2))

In [5]:
def mean_squared_error(self, X, Y):

		res = []
		for x, y in zip(X, Y):
			_, pred = self.predict(x)
			res.append(pred)

		return mean_squared_error(Y, res)

In [6]:
model = FuzzyMMC(sensitivity=1, exp_bound=0.1, animate=False)

In [7]:
model.fit(xTrain, yTrain)

In [8]:
model.score(xTest, yTest) 

0.7631578947368421

In [9]:
model.mean_squared_error(xTest, yTest)

0.23684210526315788

In [11]:
x = xTest[9]

membership, max_memb, pred = model.predict(x)
(membership, max_memb, pred)

([0.975, 0.95], 0.975, 0)

In [13]:
yTest[9]

0

In [14]:
a = np.arange (0.0, 1.1, 0.1)
parameters = {'sensitivity': a, 'exp_bound': a }
parameters['exp_bound']

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [15]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(model, parameters, cv = 5)

In [16]:
clf.fit(xTrain, yTrain)

C:\Users\rita folisi\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=<fuzzy.FuzzyMMC object at 0x000001BAB1475308>,
             iid='warn', n_jobs=None,
             param_grid={'exp_bound': array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]),
                         'sensitivity': array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [17]:
clf.cv_results_

{'mean_fit_time': array([0.07361555, 0.07379394, 0.07200766, 0.08177471, 0.07083001,
        0.0686152 , 0.06842289, 0.08137488, 0.10452094, 0.08237886,
        0.06921439, 0.04468145, 0.04069114, 0.04168701, 0.04029307,
        0.04128852, 0.04049177, 0.04847054, 0.04080586, 0.04869156,
        0.04767733, 0.03948793, 0.02912264, 0.02672162, 0.02672472,
        0.02633452, 0.02572536, 0.02733297, 0.02533298, 0.02633657,
        0.0259306 , 0.02672811, 0.02593131, 0.021942  , 0.01915469,
        0.01855683, 0.01855569, 0.01874919, 0.01835265, 0.0183506 ,
        0.01796393, 0.018537  , 0.01855044, 0.01894474, 0.01715426,
        0.01495447, 0.01436729, 0.01456132, 0.01497207, 0.0141623 ,
        0.0145555 , 0.01455355, 0.01396189, 0.01436706, 0.01476116,
        0.01395578, 0.01236753, 0.01196208, 0.01256051, 0.01256061,
        0.01277208, 0.01276674, 0.01236649, 0.01196232, 0.01256671,
        0.0129714 , 0.01336508, 0.0109776 , 0.0109745 , 0.01176958,
        0.01176753, 0.01196809,

In [18]:
clf.score(xTest, yTest) 

0.868421052631579

In [19]:
best_params = clf.best_params_
new_exp = best_params['exp_bound']
new_sensit = best_params['sensitivity']
(new_exp, new_sensit)

(0.7000000000000001, 0.1)

In [20]:
best_model = FuzzyMMC(sensitivity=new_sensit, exp_bound=new_exp, animate=False)

In [21]:
best_model.fit(xTrain, yTrain)

In [22]:
best_model.score(xTest, yTest)

0.868421052631579

In [41]:
	def MSE_membership2(self, X, Y):

		res = []
		for x, y in zip(X, Y):
			pred, _, _ = self.predict(x)
			res.append(pred)
		res = np.array(res)
		return res, mean_squared_error(Y, res[:, 1]) 

In [42]:
from sklearn.metrics import mean_squared_error
res, val = MSE_membership2(model, xTest, yTest)
val

0.5751809210526315

Ho una MSE della membership così alta perché in generale le membership sono molto alte. Quindi pur avendo alta accuratezza, avrò comunque alto MSE delle membership. Vedi sotto:

In [45]:
res [:, 1]    
# vettore delle membership di xTest. [:, 1] indica quelle relative all'appartenenza a setosa. 
# Quindi indica quanto è effettivamente setosa

array([0.975, 0.975, 0.8  , 0.95 , 1.   , 1.   , 0.975, 0.9  , 1.   ,
       0.95 , 0.75 , 0.85 , 0.875, 0.975, 0.95 , 0.775, 0.925, 0.85 ,
       0.825, 0.75 , 0.75 , 0.85 , 0.975, 0.95 , 0.775, 0.95 , 0.75 ,
       0.775, 0.75 , 1.   , 0.95 , 0.9  , 1.   , 0.75 , 0.775, 0.975,
       0.975, 0.825])

In [37]:
res [:, 0]   # indica quanto effettivamente non è setosa

array([0.875, 0.975, 0.975, 0.975, 0.975, 0.95 , 0.95 , 0.975, 0.975,
       0.975, 0.9  , 0.95 , 0.975, 0.95 , 1.   , 0.975, 1.   , 0.975,
       0.975, 0.95 , 0.975, 1.   , 1.   , 0.925, 0.975, 0.975, 0.95 ,
       1.   , 1.   , 0.925, 0.9  , 0.95 , 0.975, 0.95 , 0.925, 0.85 ,
       0.9  , 1.   ])

In [38]:
yTest

array([1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0], dtype=int64)