In [1]:
from fuzzy import *
import matplotlib.pyplot as plt
import pandas as pd
import math
import random
from sklearn.model_selection import train_test_split


In [2]:
df = pd.read_csv('iris-versicolor.csv')

df = df.sample(frac=1)


X = df.iloc[:, 1:3].values
Y = df.iloc[:,0].values
X

array([[6.9, 3.1],
       [4.8, 3.4],
       [5.7, 3.8],
       [6.8, 3. ],
       [5.4, 3.4],
       [6. , 2.9],
       [6.9, 3.1],
       [4.4, 3. ],
       [5.1, 3.7],
       [5.5, 2.4],
       [6.3, 2.5],
       [7.9, 3.8],
       [6.3, 2.8],
       [5.4, 3.4],
       [6.2, 2.8],
       [4.9, 3.1],
       [6.4, 3.2],
       [7.4, 2.8],
       [5.9, 3. ],
       [4.8, 3.4],
       [6. , 2.2],
       [5.2, 3.5],
       [6.8, 3.2],
       [5.4, 3.9],
       [6. , 2.2],
       [5. , 3.6],
       [4.7, 3.2],
       [5.6, 2.5],
       [4.6, 3.2],
       [5.8, 2.7],
       [6.7, 3. ],
       [6.1, 2.9],
       [4.5, 2.3],
       [7. , 3.2],
       [7.2, 3.6],
       [6.8, 2.8],
       [5.9, 3. ],
       [5.7, 2.9],
       [6.3, 3.3],
       [5.8, 4. ],
       [5.7, 2.5],
       [6.4, 2.8],
       [4.9, 3.1],
       [5.1, 3.4],
       [5.5, 3.5],
       [6.4, 3.2],
       [5.9, 3.2],
       [5. , 3.4],
       [5.6, 3. ],
       [6.3, 2.5],
       [4.3, 3. ],
       [6.7, 3.1],
       [6.6,

In [3]:
xTrain, xTest, yTrain, yTest = train_test_split(X,Y)

In [4]:
xTrain.shape, xTest.shape

((112, 2), (38, 2))

In [5]:
def mean_squared_error(self, X, Y):

		res = []
		for x, y in zip(X, Y):
			_, pred = self.predict(x)
			res.append(pred)

		return mean_squared_error(Y, res)

In [6]:
model = FuzzyMMC(sensitivity=1, exp_bound=0.1, animate=False)

In [7]:
model.fit(xTrain, yTrain)

In [8]:
model.score(xTest, yTest) 

0.631578947368421

In [9]:
model.mean_squared_error(xTest, yTest)

0.3684210526315789

In [10]:
x = xTest[9]

membership, max_memb, pred = model.predict(x)
(membership, max_memb, pred)

([1.0, 0.75], 1.0, 0)

In [11]:
yTest[9]

0

In [12]:
a = np.arange (0.0, 1.1, 0.1)
parameters = {'sensitivity': a, 'exp_bound': a }
parameters['exp_bound']

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [13]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(model, parameters, cv = 5)

In [14]:
clf.fit(xTrain, yTrain)

C:\Users\rita folisi\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=<fuzzy.FuzzyMMC object at 0x0000027FCF157E88>,
             iid='warn', n_jobs=None,
             param_grid={'exp_bound': array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]),
                         'sensitivity': array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [15]:
clf.cv_results_

{'mean_fit_time': array([0.12113981, 0.23228436, 0.20704122, 0.15728297, 0.14175529,
        0.18534212, 0.19645467, 0.17693205, 0.15889106, 0.13116846,
        0.12365913, 0.14391785, 0.13415513, 0.07640142, 0.07184992,
        0.06948714, 0.06943793, 0.07299733, 0.06774464, 0.0721097 ,
        0.07090912, 0.07731051, 0.05578303, 0.04686046, 0.04827118,
        0.04747915, 0.05167847, 0.04997606, 0.04766684, 0.04897103,
        0.05009036, 0.06353464, 0.07615585, 0.06596847, 0.06123466,
        0.0544539 , 0.04287882, 0.03715558, 0.03591537, 0.03626761,
        0.03273034, 0.03490124, 0.0369081 , 0.04767184, 0.03929491,
        0.0385437 , 0.03829813, 0.04012251, 0.03231316, 0.02413554,
        0.02632847, 0.04478555, 0.02713346, 0.02314448, 0.02432675,
        0.02687864, 0.02300506, 0.02255106, 0.02214046, 0.02274518,
        0.02474766, 0.02193122, 0.0211494 , 0.02114286, 0.02253799,
        0.02114882, 0.02259626, 0.01884627, 0.01735296, 0.01695461,
        0.0177608 , 0.01836171,

In [16]:
clf.score(xTest, yTest) 

0.7105263157894737

In [17]:
best_params = clf.best_params_
new_exp = best_params['exp_bound']
new_sensit = best_params['sensitivity']
(new_exp, new_sensit)

(0.9, 0.1)

In [18]:
best_model = FuzzyMMC(sensitivity=new_sensit, exp_bound=new_exp, animate=False)

In [19]:
best_model.fit(xTrain, yTrain)

In [20]:
best_model.score(xTest, yTest)

0.7105263157894737

In [21]:
	def MSE_membership2(self, X, Y):

		res = []
		for x, y in zip(X, Y):
			pred, _, _ = self.predict(x)
			res.append(pred)
		res = np.array(res)
		return res, mean_squared_error(Y, res[:, 1]) 

In [22]:
from sklearn.metrics import mean_squared_error
res, val = MSE_membership2(model, xTest, yTest)
val

0.5706907894736842

Ho una MSE della membership così alta perché in generale le membership sono molto alte. Quindi pur avendo alta accuratezza, avrò comunque alto MSE delle membership. Vedi sotto:

In [13]:
res

array([[0.975, 0.825],
       [1.   , 0.95 ],
       [0.975, 0.825],
       [0.95 , 0.7  ],
       [0.95 , 0.75 ],
       [1.   , 0.975],
       [0.975, 0.825],
       [0.9  , 0.975],
       [0.975, 0.975],
       [0.9  , 0.75 ],
       [0.95 , 0.9  ],
       [0.975, 0.975],
       [0.975, 0.925],
       [0.825, 0.9  ],
       [0.925, 0.975],
       [0.975, 0.925],
       [0.975, 0.85 ],
       [1.   , 0.95 ],
       [0.95 , 1.   ],
       [1.   , 0.875],
       [1.   , 0.95 ],
       [0.975, 0.925],
       [0.9  , 0.975],
       [0.925, 0.975],
       [0.925, 0.775],
       [0.95 , 0.925],
       [1.   , 0.75 ],
       [0.975, 1.   ],
       [0.975, 0.95 ],
       [0.975, 0.85 ],
       [0.95 , 0.9  ],
       [0.975, 0.925],
       [0.875, 0.9  ],
       [0.875, 0.975],
       [0.975, 0.75 ],
       [1.   , 0.775],
       [1.   , 0.9  ],
       [0.9  , 0.675]])

In [45]:
res [:, 1]    
# vettore delle membership di xTest. [:, 1] indica quelle relative all'appartenenza a setosa. 
# Quindi indica quanto è effettivamente setosa

array([0.975, 0.975, 0.8  , 0.95 , 1.   , 1.   , 0.975, 0.9  , 1.   ,
       0.95 , 0.75 , 0.85 , 0.875, 0.975, 0.95 , 0.775, 0.925, 0.85 ,
       0.825, 0.75 , 0.75 , 0.85 , 0.975, 0.95 , 0.775, 0.95 , 0.75 ,
       0.775, 0.75 , 1.   , 0.95 , 0.9  , 1.   , 0.75 , 0.775, 0.975,
       0.975, 0.825])

In [37]:
res [:, 0]   # indica quanto effettivamente non è setosa

array([0.875, 0.975, 0.975, 0.975, 0.975, 0.95 , 0.95 , 0.975, 0.975,
       0.975, 0.9  , 0.95 , 0.975, 0.95 , 1.   , 0.975, 1.   , 0.975,
       0.975, 0.95 , 0.975, 1.   , 1.   , 0.925, 0.975, 0.975, 0.95 ,
       1.   , 1.   , 0.925, 0.9  , 0.95 , 0.975, 0.95 , 0.925, 0.85 ,
       0.9  , 1.   ])

In [38]:
yTest

array([1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0], dtype=int64)