In [2]:
from fuzzy import *
import matplotlib.pyplot as plt
import pandas as pd
import math
import random
from sklearn.model_selection import train_test_split


In [3]:
df = pd.read_csv('iris-versicolor.csv')

df = df.sample(frac=1)


X = df.iloc[:, 1:3].values
Y = df.iloc[:,0].values
X

array([[7.2, 3. ],
       [7.7, 3.8],
       [5.1, 2.5],
       [6.3, 2.5],
       [4.7, 3.2],
       [5.2, 4.1],
       [6.3, 2.8],
       [5.7, 4.4],
       [6.2, 2.8],
       [5. , 3.5],
       [5.6, 3. ],
       [6.1, 2.9],
       [5.8, 2.8],
       [6.7, 3.3],
       [6.7, 3.1],
       [5. , 3. ],
       [6.9, 3.1],
       [5.2, 3.4],
       [6.9, 3.1],
       [5. , 3.4],
       [7.6, 3. ],
       [4.4, 2.9],
       [6.9, 3.1],
       [6.4, 2.8],
       [6.3, 3.4],
       [5.7, 2.5],
       [6. , 3.4],
       [4.6, 3.2],
       [6.1, 3. ],
       [5.5, 4.2],
       [5.5, 2.5],
       [6.6, 2.9],
       [4.5, 2.3],
       [5.4, 3.7],
       [5.4, 3.9],
       [5.2, 2.7],
       [4.9, 2.4],
       [6.4, 3.2],
       [5.1, 3.5],
       [6.3, 2.5],
       [4.6, 3.6],
       [6. , 2.7],
       [5.8, 4. ],
       [5.7, 2.8],
       [6.7, 3.1],
       [6.1, 2.8],
       [5.5, 2.4],
       [6.2, 3.4],
       [6.4, 2.9],
       [5.4, 3.4],
       [5.1, 3.8],
       [6.7, 3. ],
       [6.3,

In [4]:
xTrain, xTest, yTrain, yTest = train_test_split(X,Y)

In [5]:
xTrain.shape, xTest.shape

((112, 2), (38, 2))

In [6]:
def mean_squared_error(self, X, Y):

		res = []
		for x, y in zip(X, Y):
			_, pred = self.predict(x)
			res.append(pred)

		return mean_squared_error(Y, res)

In [7]:
model = FuzzyMMC(sensitivity=1, exp_bound=0.1, animate=False)

In [8]:
model.fit(xTrain, yTrain)

In [9]:
model.score(xTest, yTest) 

0.6578947368421053

In [10]:
model.mean_squared_error(xTest, yTest)

0.34210526315789475

In [11]:
x = xTest[9]

membership, pred = model.predict(x)
(membership, pred)

(0.975, 0)

In [12]:
xTest[9]

array([6.3, 2.9])

In [13]:
yTest[9]

0

In [14]:
a = np.arange (0.0, 1.1, 0.1)
parameters = {'sensitivity': a, 'exp_bound': a }
parameters['exp_bound']

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [15]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(model, parameters, cv = 5)

In [16]:
clf.fit(xTrain, yTrain)

C:\Users\rita folisi\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=<fuzzy.FuzzyMMC object at 0x000001931F50A208>,
             iid='warn', n_jobs=None,
             param_grid={'exp_bound': array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]),
                         'sensitivity': array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [17]:
clf.cv_results_

{'mean_fit_time': array([0.07880297, 0.0808857 , 0.09275651, 0.07739263, 0.07041078,
        0.0777987 , 0.08038526, 0.07371693, 0.07180114, 0.07241211,
        0.09274492, 0.06462722, 0.04268546, 0.03889632, 0.04089046,
        0.03849716, 0.0400929 , 0.03949418, 0.03949409, 0.03889585,
        0.03909554, 0.04029255, 0.02712731, 0.02253962, 0.02333746,
        0.02434044, 0.02532625, 0.02214017, 0.02353711, 0.02293911,
        0.02214084, 0.02473416, 0.02672853, 0.02154193, 0.01795192,
        0.01735368, 0.01954865, 0.01973772, 0.01815066, 0.01774673,
        0.01795173, 0.01815143, 0.01814532, 0.01774545, 0.01835093,
        0.01675515, 0.01635613, 0.01655574, 0.01535935, 0.01635618,
        0.01695514, 0.01675529, 0.0163559 , 0.01615705, 0.01715412,
        0.01555834, 0.01256638, 0.01316495, 0.0119679 , 0.01256618,
        0.01316462, 0.01236668, 0.0133646 , 0.01257172, 0.01176772,
        0.01375828, 0.01276555, 0.01138248, 0.01096511, 0.01096301,
        0.01196842, 0.01136961,

In [18]:
clf.score(xTest, yTest) 

0.6578947368421053

In [46]:
best_params = clf.best_params_
new_exp = best_params['exp_bound']
new_sensit = best_params['sensitivity']
(new_exp, new_sensit)

(0.7000000000000001, 0.1)

In [52]:
best_model = FuzzyMMC(sensitivity=new_sensit, exp_bound=new_exp, animate=False)

In [53]:
best_model.fit(xTrain, yTrain)

In [54]:
best_model.score(xTest, yTest)

0.6578947368421053

In [55]:
best_model2 = FuzzyMMC(sensitivity=0.1, exp_bound=0.6000000000000001, animate=False)

In [56]:
best_model2.fit(xTrain, yTrain)

In [58]:
best_model2.score(xTest, yTest)

0.6842105263157895