In [1]:
from fuzzy import *
import matplotlib.pyplot as plt
import pandas as pd
import math
import random
from sklearn.model_selection import train_test_split


In [2]:
df = pd.read_csv('iris-versicolor.csv')

df = df.sample(frac=1)


X = df.iloc[:, 1:3].values
Y = df.iloc[:,0].values
X

array([[7.7, 2.8],
       [6.1, 3. ],
       [6.8, 3. ],
       [7.7, 3.8],
       [4.9, 3. ],
       [7. , 3.2],
       [6.2, 2.2],
       [5.3, 3.7],
       [5.8, 2.7],
       [5.9, 3. ],
       [4.4, 3. ],
       [4.8, 3.1],
       [5.7, 2.9],
       [6.9, 3.2],
       [5. , 3.2],
       [5.1, 3.3],
       [5.9, 3.2],
       [5.2, 4.1],
       [6.3, 2.9],
       [5.7, 3.8],
       [7.9, 3.8],
       [5. , 2. ],
       [6.3, 3.3],
       [5.1, 3.8],
       [5. , 3.6],
       [7.6, 3. ],
       [5.5, 2.4],
       [5.6, 2.8],
       [4.6, 3.2],
       [6.5, 3. ],
       [5.7, 2.8],
       [6.4, 2.7],
       [6.7, 2.5],
       [5.1, 2.5],
       [4.4, 2.9],
       [6.2, 2.8],
       [4.6, 3.1],
       [6.4, 3.2],
       [4.4, 3.2],
       [6.3, 2.5],
       [4.9, 2.4],
       [4.6, 3.6],
       [5. , 3.5],
       [5.8, 2.6],
       [5.8, 2.7],
       [4.3, 3. ],
       [5.6, 2.9],
       [5. , 3.4],
       [5.4, 3. ],
       [7.2, 3.6],
       [5.4, 3.7],
       [6.1, 2.6],
       [5.4,

In [3]:
xTrain, xTest, yTrain, yTest = train_test_split(X,Y)

In [4]:
xTrain.shape, xTest.shape

((112, 2), (38, 2))

In [5]:
def mean_squared_error(self, X, Y):

		res = []
		for x, y in zip(X, Y):
			_, pred = self.predict(x)
			res.append(pred)

		return mean_squared_error(Y, res)

In [6]:
model = FuzzyMMC(sensitivity=1, exp_bound=0.1, animate=False)

In [7]:
model.fit(xTrain, yTrain)

In [8]:
model.score(xTest, yTest) 

0.7368421052631579

In [9]:
model.mean_squared_error(xTest, yTest)

0.2631578947368421

In [10]:
x = xTest[9]

membership, pred = model.predict(x)
(membership, pred)

(0.975, 0)

In [11]:
xTest[9]

array([4.6, 3.1])

In [12]:
yTest[9]

0

In [13]:
a = np.arange (0.0, 1.1, 0.1)
parameters = {'sensitivity': a, 'exp_bound': a }
parameters['exp_bound']

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [16]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(model, parameters, cv = 5)

In [17]:
clf.fit(xTrain, yTrain)

C:\Users\rita folisi\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=<fuzzy.FuzzyMMC object at 0x0000018ED0BE68C8>,
             iid='warn', n_jobs=None,
             param_grid={'exp_bound': array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]),
                         'sensitivity': array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [20]:
clf.cv_results_

{'mean_fit_time': array([0.09516792, 0.08919902, 0.09974771, 0.09434633, 0.09455476,
        0.1085166 , 0.09275603, 0.09754362, 0.11359949, 0.09784412,
        0.11148758, 0.07829895, 0.06303191, 0.04965639, 0.07860284,
        0.05924149, 0.06455073, 0.10357895, 0.1042048 , 0.09135547,
        0.08280425, 0.05345669, 0.04488955, 0.03856688, 0.04857297,
        0.03550482, 0.04215975, 0.04288325, 0.03530526, 0.03266892,
        0.03969107, 0.04877877, 0.04069123, 0.03191814, 0.0281249 ,
        0.02752609, 0.0297205 , 0.02992263, 0.02812462, 0.0283154 ,
        0.02902875, 0.02852316, 0.02812481, 0.02664905, 0.0254283 ,
        0.02134237, 0.01974492, 0.02078228, 0.02094445, 0.02105227,
        0.02078099, 0.0239419 , 0.02772384, 0.02413664, 0.02273927,
        0.02353716, 0.01755266, 0.02427726, 0.03131909, 0.02831063,
        0.0208581 , 0.02105136, 0.02057681, 0.01855145, 0.03769794,
        0.02194214, 0.02014599, 0.01675539, 0.01695471, 0.01860747,
        0.01815143, 0.01694293,

In [21]:
clf.score(xTest, yTest) 

0.8157894736842105

In [28]:
clf.best_params_

{'exp_bound': 0.6000000000000001, 'sensitivity': 0.5}

In [29]:
best_model = FuzzyMMC(sensitivity=0.5, exp_bound=0.60, animate=False)

In [30]:
best_model.fit(xTrain, yTrain)

In [ ]:
best_model.score(